%macro strr 2
	mov esi,%1
	mov ecx,%2
mm:
	cmp byte[esi],0
	je end
	inc dword[ecx]
	inc esi
	jmp mm
end:
	
%endmacro

%macro strr1 3
        mov esi,%1
	mov edi,%2
	mov ecx,%3
        add esi,ecx
	dec esi
%%cpp:  
       mov al,byte[esi]
       mov byte[edi],al
       dec esi
	inc edi
 	dec ecx
	cmp ecx,0
	jne %%cpp
%%end:
        mov eax,4
        mov ebx,1
        mov ecx,%2
        mov edx,%3
        int 0x80

%endmacro
